--liquibase formatted sql


--changeset john.zhao:svt_autochg_tdv_dev.tables.demo_tbl2_bkp labels:tmp,demo context:dev
--comment: Create table HSETL_WORK_DEV2.DEMO_TBL2_BKP

CREATE SET TABLE HSETL_WORK_DEV2.DEMO_TBL2_BKP (
DEMO_TBL_KEY CHAR(32) NOT NULL PRIMARY KEY,
CRET_TS TIMESTAMP NOT NULL,
UPDT_TS TIMESTAMP NOT NULL,
CHK_SUM_TXT CHAR(32) NOT NULL,
CMMNT_TXT VARCHAR(1000) NOT NULL,
CRET_BY VARCHAR(1000),
ACT_IND CHAR(1) NOT NULL
);

--changeset john.zhao:svt_autochg_tdv_dev.tables.demo_tbl2_bkp labels:tmp,demo context:dev
--comment: Create table HSETL_WORK_DEV2.demo_tbl2_bkp

CREATE SET TABLE HSETL_WORK_DEV2.DEMO_TBL2 (
DEMO_TBL_KEY CHAR(32) NOT NULL PRIMARY KEY,
CRET_TS TIMESTAMP NOT NULL,
UPDT_TS TIMESTAMP NOT NULL,
CHK_SUM_TXT CHAR(32) NOT NULL,
CMMNT_TXT VARCHAR(1000) NOT NULL,
CRET_BY VARCHAR(1000),
ACT_IND CHAR(1) NOT NULL
);
--rollback DROP TABLE HSETL_WORK_DEV2.DEMO_TBL2;
