apiVersion: batch/v1
kind: Job
metadata:
  name: %JOB_NAME%
  namespace: default
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: %DATA_ORG%-tdv-liq-int
        name: %JOB_NAME%
    spec:
      containers:
      - name: liquibase
        image: 302619437920.dkr.ecr.us-east-1.amazonaws.com/dna-ad/%ECR_TDV_LIQUIBASE%:%IMAGE_TAG%
        command: ['/bin/bash']
        args: ['-c', '/liquibase/scripts/bteq-update.sh']
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data
          name: data
        env:
        - name: ENV
          value: INT
        - name: TDV_LOGMECH
          value: %TDV_LOGMECH%
        - name: TDV_LIQ_USR
          valueFrom:
            secretKeyRef:
              key: TDV_LIQ_USR
              name: %DATA_ORG%-tdv-liq-usr-int
        - name: TDV_LIQ_PSW
          valueFrom:
            secretKeyRef:
              key: TDV_LIQ_PSW
              name: %DATA_ORG%-tdv-liq-psw-int
      restartPolicy: Never
      volumes:
        - name: data
          emptyDir: {}
