---
DEV:
  ENV: DEV
  #AWS_FED_SA: SVP_ENT360_AWS_DEV
  AWS_FED_ACCOUNT: '302619437920'
  AWS_FED_CRED: 360-sa-dev
  GLUE_S3_BUCKET: da-ent360-tdv-gluescript-dev
  MWAA_BUCKET: da-ent360-api-mwaa-bucket-dev
  CHANGELOG_FILE: main.changelog.xml
  TDV_LIQ_CRED: "OSS_TDV_DEV2"
  TDV_UNITTEST_SA: "autochange-user-dev"
  TDV_LOGMECH: "TD2"                                   #available values are LDAP and TD2 depending on Env
  
TEST:
  ENV: TEST
  #AWS_FED_SA: SVP_ENT360_AWS_TST
  AWS_FED_ACCOUNT: '919498567002'
  AWS_FED_CRED: 360-sa-test
  GLUE_S3_BUCKET: da-ent360-tdv-gluescript-test
  MWAA_BUCKET: da-ent360-api-mwaa-bucket-test
  CHANGELOG_FILE: main.changelog.xml
  TDV_LIQ_CRED: "OSS_TDV_QA"
  TDV_UNITTEST_SA: "autochange-user-int"
  TDV_LOGMECH: "TD2"                                   #available values are LDAP and TD2 depending on Env

PROD:
  ENV: PROD
  #AWS_FED_SA: SVP_ENT360_AWS_PRD
  AWS_FED_ACCOUNT: '355113922316'
  AWS_FED_CRED: 360-sa-prod
  GLUE_S3_BUCKET: da-ent360-tdv-gluescript-prod
  MWAA_BUCKET: da-ent360-api-mwaa-bucket-prod
  CHANGELOG_FILE: main.changelog.xml
  TDV_LIQ_CRED: "OSS_TDV_PROD"
  TDV_LOGMECH: "LDAP"                                   #available values are LDAP and TD2 depending on Env

COMMON:
  RULES_ENGINE: "OSS"               #available values are: oss and Enterprise Rules Engine  
  ECR_TDV_LIQUIBASE: "oss-tdv-liquibase"
  ECR_TDV_UNITTESTING: 'tdv-unittest-custom-builds'
  AWS_FED_ROLENAME: "JENKINSTERRAFORMDEPLOY"
  K8S_NAME: ad-data-services
  K8S_NAMESPACE: "tdv"
  CX_TEAM: tdv-pipeline
  CX_PROJECT_NAME: "tdv-oss-demo"
  CX_PROJECT_PATH: CxServer/Cigna/
  TEAM_EMAIL_ID: "TDV_PIPELINE_ADMIN@Cigna.com"
  DDL_PROJECT_NAME: "tdv-oss-demo"
  JENKINS_CREDS_ID: "JENKINS_API_CREDS"
  CX_CREDENTIALS_ID: "tdv-pipeline-checkmarx"
  GITHUB_TOKEN_CREDS_ID: "SVPDEVOP-CIG-CLONEA_UserPw"
  WEBHOOK_GITHUB_TOKEN_ID: "WEBHOOK_GITHUB_TOKEN"
