---
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: kaniko
  containers:
    - name: "jnlp"
      image: "registry.sunvalle.net/enterprise-devops/conduit-jnlp:cloudbees-2.235.5.1"
      workingDir: "/home/jenkins/agent"
      imagePullPolicy: Always
      tty: true
      env:
          - name: HOME
            value: /home/jenkins
      resources:
        requests:
          cpu: '100m'
          memory: '512Mi'
        limits:
          cpu: '250m'
          memory: '512Mi'
      volumeMounts:
        - name: shared-jenkins-workspace
          mountPath: /home/jenkins/agent/workspace
          readOnly: false
        - name: shared-jenkins-aws-creds
          mountPath: /home/jenkins/.aws
          readOnly: false
    - name: kaniko
      image: registry.sunvalle.net/enterprise-devops/conduit-kaniko:debug-v1.5.0
      command:
        - cat
      tty: true
      env:
        - name: 'AWS_SHARED_CREDENTIALS_FILE'
          value: '/home/jenkins/.aws/credentials'
        - name: 'AWS_PROFILE'
          value: 'saml'
      resources:
        requests:
          cpu: '500m'
          memory: '750Mi'
        limits:
          cpu: '750m'
          memory: '1Gi'
      volumeMounts:
        - name: shared-jenkins-aws-creds
          mountPath: '/home/jenkins/.aws'
          readOnly: false
        - name: shared-jenkins-workspace
          mountPath: /home/jenkins/agent/workspace
          readOnly: false
    - name: toolkit
      image: registry.sunvalle.net/svci-digital/digedge-toolkit:latest
      env:
        - name: 'AWS_PROFILE'
          value: 'saml'
        - name: 'AWS_SHARED_CREDENTIALS_FILE'
          value: '/home/jenkins/.aws/credentials'
      resources:
        limits:
          cpu: "200m"
          memory: "200Mi"
        requests:
          cpu: "100m"
          memory: "200Mi"
      tty: true
      workingDir: /home/jenkins/agent
      imagePullPolicy: Always
      volumeMounts:
        - name: shared-jenkins-workspace
          mountPath: /home/jenkins/agent/workspace
          readOnly: false
        - name: shared-jenkins-aws-creds
          mountPath: '/home/jenkins/.aws'
          readOnly: false
    - name: cx-toolshack
      image: registry.sunvalle.net/dev-sec-ops/checkmarx-toolshack
      resources:
          requests:
              cpu: 150m
              memory: 150Mi
          limits:
              cpu: 1000m
              memory: 1000Mi
      imagePullPolicy: Always
      workingDir: /home/jenkins/agent
      volumeMounts:
        - name: shared-jenkins-workspace
          mountPath: /home/jenkins/agent/workspace
          readOnly: false
      tty: true      
    - name: rules-engine
      image: registry-dev.sunvalle.net/tdv-pipeline/oss-rules-engine:un_re_image-v1.1
      command: ['/bin/bash']
      env:
        - name: 'AWS_PROFILE'
          value: 'saml'
        - name: 'AWS_SHARED_CREDENTIALS_FILE'
          value: '/home/jenkins/.aws/credentials'
      resources:
        limits:
          cpu: "500m"
          memory: "1Gi"
        requests:
          cpu: "200m"
          memory: "500Mi"
      tty: true
      imagePullPolicy: Always
      volumeMounts:
        - name: shared-jenkins-workspace
          mountPath: /home/jenkins/agent/workspace
  volumes:
    - name: shared-jenkins-workspace
      emptyDir: {}
    - name: shared-jenkins-aws-creds
      emptyDir: {}
